# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
- openjdk14

services:
  - postgresql

before_install:
  - chmod +x mvnw

install: true
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# create psql database
before_script:
  - psql -c 'create database job4j_auto-trader;' -U postgres


# Отправлять уведомление на почту laiwiense@gmail.com
notifications:
  email:
    recipients:
      -laiwiense@gmail.com
    on_success: never # default: change
    on_failure: always # default: always